spring:
  datasource:
    url: jdbc:mysql://localhost/empresa?serverTimezone=UTC
    username: root
    password: 1i9l6p205
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


